Repository PlayFab/gsdk, pull requests merged in 2021-11, with the labels that each got.

#103 Experimental Go GSDK
  experimental/go/README.md
  experimental/go/go.mod
  experimental/go/go.sum
  experimental/go/gsdk.go
  experimental/go/gsdk_test.go
  experimental/go/internalgsdk.go
  experimental/go/logger.go
  experimental/go/types.go
Labels: experimental

#109 Wrapped setting up default server around if server clause
  UnrealPlugin/ThirdPersonMPGSDKSetup.md
Labels: documentation

#107 Fixed typo in include statements
  UnrealPlugin/Source/PlayfabGSDK/Private/GSDKConfiguration.cpp
  UnrealPlugin/Source/PlayfabGSDK/Private/GSDKInternal.cpp
  UnrealPlugin/Source/PlayfabGSDK/Private/GSDKUtils.cpp
  UnrealPlugin/Source/PlayfabGSDK/Private/PlayfabGSDK.cpp
Labels: bug
